# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.12
      
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go build go-ios.go
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/artifacts
      - run: 
          command: |
            go test -v -coverprofile=c.out ./...
            go tool cover -html=c.out -o coverage.html
            mv coverage.html /tmp/artifacts 
      - codecov/upload:
          file: /tmp/artifacts
